### ISSUE TITLE
Initial spin out of package

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/markdown-it-myst#1]
I am working on spinning out the package. I have put together a simple demo, should be able `yarn install; yarn start` to play around with it.

![myst-demo](https://user-images.githubusercontent.com/913249/88117176-a8195280-cb77-11ea-8a7c-8a967fc93930.gif)

I will continue to work here probably for the next week or so, then hopefully it will begin to mature.

cc @chrisjsewell or @choldgraf

**Comment by choldgraf** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉

**Comment by chrisjsewell** [comment]
FTI @rowanc1 markdown-it-containers are now in myst-parser 😄 https://myst-parser.readthedocs.io/en/latest/using/syntax.html#admonition-directives-special-syntax-optional

**Comment by rowanc1** [comment]
That is awesome. Thanks for the update here, I have fallen off the wagon for the last week or so, hoping to get back to contributing in the next few weeks, have been following along to some of your other changes as well!

**Comment by chrisjsewell** [comment]
Oh yeh no problem, I know these things can be periodic. I could do with falling of the wagon at some point lol 🍻🍹

**Comment by rowanc1** [comment]
Closing this, will move into some more targeted issues soon.
