### ISSUE TITLE
Transfer to ExecutableBooks

### ISSUE THREAD

**Issue by rowanc1** [executablebooks/markdown-it-myst#2]
I have started the request, and will wait for @choldgraf to accept on the other side!

**Comment by choldgraf** [comment]
I still haven't seen a request in my inbox etc 🤷‍♀️

**Comment by rowanc1** [comment]
Quite right.

`You don’t have the permission to create public repositories on executablebooks`

Do you think you could give me admin-ish access to start the transfer?

Or -- I will also try giving you admin on this and fiddling with my orgs permissions for transfer rights.

**Comment by rowanc1** [comment]
Ok, you should have an invite as an admin on this repo. And then you should be able to transfer it out (I think?!).

**Comment by choldgraf** [comment]
ah yeah that worked - OK I just transferred it and made you an admin: https://github.com/executablebooks/markdown-it-myst/invitations

**Comment by rowanc1** [comment]
Awesome, very exciting. 🚀
