### ISSUE TITLE
SHAME

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/markdown-it-myst#3]
we need to call the emoji police

![chrome_2020-07-23_14-05-40](https://user-images.githubusercontent.com/1839645/88338719-9eb1f680-cced-11ea-9567-d87e5d33c5a3.png)

**Comment by rowanc1** [comment]
Oh man, this is me trying out the "auto" publish/commit/tag capabilities of yarn. Will require upstream PRs to get this fixed. 💥

**Comment by choldgraf** [comment]
lol I'm all for auto-incrementing this kinda stuff if it works well, so don't mistake my shaming for a 👎

**Comment by rowanc1** [comment]
(I am going to quietly close this issue!)

**Comment by choldgraf** [comment]
![](https://media.giphy.com/media/vX9WcCiWwUF7G/giphy.gif)
