### ISSUE TITLE
Decide on scope and major functionality of this repository

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/markdown-it-myst#32]
I think there are a few different visions for the scope and functionality for `markdown-it-myst`. We should align on these high-level questions to make sure that we have the same goals in mind for development.

@rowanc1's initial implementation here seems focused on mimicking the MyST Parser in Python (at least in terms of functionality). It focuses on "parsing to tokens and rendering to HTML using markdown-it", but doesn't have any notion of a multi-document model. In [@chrisjsewell's PR](https://github.com/executablebooks/markdown-it-myst/pull/31/files#diff-b0929dacd4f1fc192cd308c1a9db2e85154ea742ccec315518e659d7f6a3efc7) he lays out a more fully-functional picture for bringing in the same functionality as Sphinx and Jupyter Book, rather than just the MyST parser. 

It feels like these two approaches have different implications for how much complexity and maintenance burden we are taking on, as well as how this tool fits in with other potential tools in the ecosystem, so we should make sure we are on the same page about this.

Can we use this issue to agree on a strategy for how we're going to tackle "MyST in Javascript", and what scope this repository should have? I'd be interested in hearing @chrisjsewell and @rowanc1's thoughts on this.

**Comment by chrisjsewell** [comment]
@choldgraf me and @rowanc1 are meeting on Thursday

**Comment by chrisjsewell** [comment]
But firstly, as I have started to do with markdown-it-plugin-template and markdown-it-amsmath, we should put in place the comparative python/JavaScript plugins for markdown-it

**Comment by chrisjsewell** [comment]
> @rowanc1's initial implementation here seems focused on mimicking the MyST Parser in Python

well that is where I disagree a bit; that’s exactly what it does not do: some of the markdown-it plugins are specifically designed to just be “entry points” for passing to sphinx, then utilising its functionality (and so not bothered about the actual rendering). Obviously we do not have sphinx in JavaScript, so have to think a little differently.

**Comment by rowanc1** [comment]
Wrote a big long issue in #34 on the plan that we agreed upon with @chrisjsewell and @fwkoch today. I think that this makes sense, although still a few outstanding things to work out. I am going to close this!
