### ISSUE TITLE
markdown-it options as parameters instead of a hardcode

### ISSUE THREAD

**Issue by efengler** [executablebooks/markdown-it-myst#9]
I wanted to render an md file containing html tags, but they weren't parsed and they were displayed as paragraph content. Then I saw this part in your `src/index.ts`:

```
export default function MyST() {
  const tokenizer = MarkdownIt('commonmark', { html: false });
  //...
```

I think that MarkdownIt options should be options to MyST as well. Especially that this behavior is inconsistent with the Python parser - running default_parser for html parses html tags normally.

**Comment by rowanc1** [comment]
Wow, @efengler I missed this comment completely, sorry for the radio silence!

Completely agree. I am starting more work on this at the moment and will address this soon! Thanks for the feedback. :)

**Comment by rowanc1** [comment]
This should now be in, you can access this from the outside now!
